### PR TITLE
Fixed alpha initialization bug

### PR DESCRIPTION
**Pull request by ravigarg27**
Default value of alpha should be 0.5 instead of 0.05

### CODE REVIEW

**Comment by jasmainak** [comment]
LGTM, merging

**Comment by jasmainak** [comment]
thanks @ravigarg27 ! 

you might want to add the email-id you used to commit to the list of recognized email addresses on github. Right now, the commit cannot be traced back to you

**Comment by ravigarg27** [comment]
Ahh it was missing from my local git config. I guess li8 for this, for future I believe it will be done. Thanks for letting me know.

**Comment by pavanramkumar** [comment]
Thanks for this @ravigarg27

**Pull request merged**
