### PR TITLE
PEP8 fixes

### PR DESCRIPTION
**Pull request by jasmainak**
hey guys! My editor was screaming out loud when I tried to edit anything here. So I fixed (most of the) pep8 and flake8 issues that I encountered. I decided not to touch anything that may have been called from the ipython notebooks.

### CODE REVIEW

**Comment by titipata** [comment]
@jasmainak this is great!

**Comment by jasmainak** [comment]
okay I am done :) Hope I didn't break anything ... I noticed that the ipython notebook doesn't run on master (gives an error).

Also, I noticed that `np.random` is used but the seed is not set. Later, must sleep now :) @pavanramkumar @titipata feel free to merge if you're happy.

**Comment by titipata** [comment]
@jasmainak, awww, I don't have permission to merge. I have pull-request [here](https://github.com/pavanramkumar/pyglmnet/pull/9) too where I rearrange the class to more scikit-learn style (kind of overlap with you've done). Either @pavanramkumar merges mine or yours first is good.

**Comment by pavanramkumar** [comment]
@titipata @jasmainak Thanks guys! Perfect place for my github gurus to meet. I'll merge this pull request first and then add in a couple of commits I liked in the other one

**Comment by titipata** [comment]
I can create new pull-request @pavanramkumar.

**Comment by pavanramkumar** [comment]
Ok I'll wait for your pull request then @titipata 
Liked your documentation edits to the class and its methods. Also the readme updates were great.

**Comment by pavanramkumar** [comment]
@jasmainak why replace if-else with dict? dict implementation computes all variants in each pass. computationally more expensive!

**Comment by jasmainak** [comment]
oops, my bad! what you need to do is replace: `qu[self.distr]` by `qu[self.distr](z)` and they will be equivalent. I used `dict` because it is more compact and also I think there is an overhead with the branching in if-else which is not there in dict. But it's probably negligible if you are not doing many calls to that function.

**Comment by jasmainak** [comment]
also, just to check I tried this in ipython notebook

```py
import time

def square(x):
    time.sleep(0.1)  # computation time
    return x ** 2

def cube(x):
    time.sleep(0.1)
    return x ** 3

def run_ifelse(func, x):
    if func == 'square':
        return square(x)
    elif func == 'cube':
        return cube(x)

def run_dict(func, x):
    options = dict(square=square, cube=cube)
    return options[func](x)

func, x = 'square', 2
%timeit run_ifelse(func, x)
%timeit run_dict(func, x)
```

and I get

```py
10 loops, best of 3: 100 ms per loop
10 loops, best of 3: 100 ms per loop
```

**Comment by jasmainak** [comment]
see also: https://gist.github.com/Eric89GXL/be9052ff4cf602796599

**Comment by pavanramkumar** [comment]
@jasmainak this is great, thanks! it's potentially important because this is called in the innermost loop in each iteration. i've fixed as you suggested, for now

**Comment by jasmainak** [comment]
@pavanramkumar I think you misunderstood what I was suggesting (my bad since I didn't explain fully, hoping that you would understand from the example I gave). You will also have to remove the `z` in the dict. Right now, if you run nosetest you get an error:

```py
======================================================================
ERROR: Test glmnet.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tsi/doctorants/mainak/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tsi/doctorants/mainak/pyglmnet/tests/test_pyglmnet.py", line 22, in test_glmnet
    y_train = glm.simulate(beta0, beta, X_train)
  File "/tsi/doctorants/mainak/pyglmnet/pyglmnet/pyglmnet.py", line 352, in simulate
    y = np.random.poisson(self.lmb(beta0, beta, X))
  File "/tsi/doctorants/mainak/pyglmnet/pyglmnet/pyglmnet.py", line 112, in lmb
    l = self.qu(z)
  File "/tsi/doctorants/mainak/pyglmnet/pyglmnet/pyglmnet.py", line 107, in qu
    return qu[self.distr](z)
TypeError: 'numpy.ndarray' object is not callable

----------------------------------------------------------------------
Ran 1 test in 0.062s
```

**Comment by pavanramkumar** [comment]
Still getting errors. When I run:

```nosetests tests/test_pyglmnet.py --with-coverage```

I get:
```
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
F
======================================================================
FAIL: Test glmnet.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pavanramkumar/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pavanramkumar/Documents/Work/NUProjects/25-codeglm/pyglmnet/tests/test_pyglmnet.py", line 30, in test_glmnet
    assert_allclose(density_, density, atol=0.02)  # check density
  File "/Users/pavanramkumar/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/pavanramkumar/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.02

(mismatch 100.0%)
 x: array(0.07)
 y: array(0.1)

----------------------------------------------------------------------
Ran 1 test in 0.365s

FAILED (failures=1)
```

**Comment by jasmainak** [comment]
okay, this error is just telling you that the density of the estimated coefficients is 0.07 as opposed to 0.1 for the true coefficients. I had set a tolerance of 0.02 but maybe that's too restrictive? You could increase it to 0.05 I think

**Comment by jasmainak** [comment]
also, you need to install `coverage` with `pip` or `easy_install`

**Pull request merged**
