### PR TITLE
Multinomial intercept gradient and LL fix (Close #10)

### PR DESCRIPTION
**Pull request by daniel-acuna**
Previous code was wrongly collapsing gradient of intercept parameters. Also, logLL was retuning negative log-likelihood.

### CODE REVIEW

**Comment by daniel-acuna** [comment]
How is my code producing fails when the tests are only about Poisson link? Travis CI pls :)

**Comment by jasmainak** [comment]
actually, the test fails on the current `master` branch too ... let me try to see when it started failing

**Comment by jasmainak** [comment]
@pavanramkumar is the culprit ;) This is the commit that broke the tests: https://github.com/pavanramkumar/pyglmnet/commit/35b40478431faf2e8249f80a5dc444ce817d99c5

**Comment by daniel-acuna** [comment]
I know that Knuth didn't say "Early testing is the root of all evil"... but he might have thought about it. Let me try and solve the issue.

**Comment by titipata** [comment]
https://github.com/jayphelps/git-blame-someone-else << @pavanramkumar, you always have a chance.

**Comment by jasmainak** [comment]
I think you need to change this line to make Travis happy: https://github.com/pavanramkumar/pyglmnet/blob/master/tests/test_pyglmnet.py#L27

**Comment by jasmainak** [comment]
The rule is to add a test whenever you find a bug :)

**Comment by daniel-acuna** [comment]
Thanks for your help @jasmainak 
I am not well versed in tests, but the code in the README.md `nosetests tests/test_glmnet.py` complains that I am missing module `test_glmnet`. The tests only ran once I used `nosetests` or `nosetests tests`. Am I doing something wrong? Should I update the README too?

**Comment by jasmainak** [comment]
oops, it should be `nosetests tests/test_pyglmnet.py` since that's the name of the file. You can also use the name of any folder that the tests are in. For example `nosetests tests` or `nosetests .` should work equally well

**Comment by jasmainak** [comment]
yep, you can fix the README!

**Comment by daniel-acuna** [comment]
thanks!

**Comment by pavanramkumar** [comment]
sorry couldn't get to any of this earlier today. nice work on the fixes! lol @titpata for https://github.com/jayphelps/git-blame-someone-else

**Pull request merged**
