### PR TITLE
[MRG] Theme bootstrap

### PR DESCRIPTION
**Pull request by jasmainak**
Taking over https://github.com/pavanramkumar/pyglmnet/pull/121

Let's see if Circle is happy

### CODE REVIEW

**Comment by jasmainak** [comment]
This is how it looks: https://22-57420386-gh.circle-artifacts.com/0//home/ubuntu/pyglmnet/doc/_build/html/index.html

**Comment by pavanramkumar** [comment]
It looks great but can we have the navigation menu vertically? I like the layout in http://keras.io

**Comment by jasmainak** [comment]
oh well, that's the `read_the_docs` theme which we already have. I don't really recall why the older PR was made by @the872. If you know each other IRL, maybe you can discuss if this is really necessary.  If you don't want want a bootstrap theme, let's close this PR? I'm trying to close open issues and stale PRs so that we converge on the milestone 0.1 (actually, I just noticed this was not part of the milestone. So, my bad ...)

**Comment by pavanramkumar** [comment]
I personally prefer `read_the_docs`, so let's ignore this for `0.1`.

**Comment by jasmainak** [comment]
okay I'll close the PR. If anyone feels compelled, they can reopen it

**Comment by pavanramkumar** [comment]
ok thanks for this anyway @jasmainak and sorry you had to spend the extra time on it!

**Pull request closed without merging**
