### PR TITLE
Add installer so it can be accessed from any folder

### PR DESCRIPTION
**Pull request by jasmainak**
just copy pasted the setup file from another repo with some minor modifications

If you want to work on it while it is installed, just do:

```python setup.py develop install```

### CODE REVIEW

**Comment by titipata** [comment]
@jasmainak I would be great if you can move `pyglmnet` into a package also.

**Comment by pavanramkumar** [comment]
awesome! so running ```python setup.py develop install``` will allow you to install and develop? then you can push back to github in the usual way?

**Comment by titipata** [comment]
Yess, now you can follow readme setup and can import `pyglmnet` in from directory.

**Comment by jasmainak** [comment]
@pavanramkumar yep!

You can also do the usual install `python setup.py install` or `python setup.py --user install` etc.

**Pull request merged**
