### PR TITLE
WIP: move docs to sphinx_gallery

### PR DESCRIPTION
**Pull request by jasmainak**
closes https://github.com/pavanramkumar/pyglmnet/issues/33

@titipata I'll give you push access to my repo so you can directly push to this branch.

To build the documentation, you need to do `make html` inside the `doc` folder.

### CODE REVIEW

**Comment by titipata** [comment]
thanks @jasmainak, I will put documentation directly there.

**Comment by jasmainak** [comment]
I would suggest that you can finish `plot_poisson.py` ... let's work on different parts of the code so as to avoid merge conflicts.

**Comment by jasmainak** [comment]
For the lazy folks:

http://perso.telecom-paristech.fr/~mjas/html/
and
http://perso.telecom-paristech.fr/~mjas/html/auto_examples/plot_poisson.html#sphx-glr-auto-examples-plot-poisson-py
etc.

**Comment by pavanramkumar** [comment]
@jasmainak this looks great, but i think @titipata was able to do this recently. what he couldn't figure out was customizing the style to give it an appearance like this: http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py

**Comment by jasmainak** [comment]
You mean like [this](/home/mainak/Desktop/projects/pyglmnet/doc/_build/html)? ;) I just changed the theme for now (see last commit) but you can also add custom `css` to make it look even better :)

**Comment by jasmainak** [comment]
you can add the `css` in a `_static` folder ... we can copy how sphinx-gallery does it if that's what you want to start with ...

**Comment by jasmainak** [comment]
@titipata let me know if you need help with building the docs. Ideally, we should replace the notebooks with the sphinx docs in a single PR.

**Comment by titipata** [comment]
Roger @jasmainak, I will go over it tonight and see how far I can do. Thanks again for setting documentation up!

**Comment by jasmainak** [comment]
Woops @pavanramkumar this PR was still "work in progress". But okay, I'll
let you guys continue on master.

**Comment by titipata** [comment]
@pavanramkumar, LOL, don't rush.

**Comment by pavanramkumar** [comment]
Sorry my bad! Thought plan was to have @titipata submit new PR

**Comment by titipata** [comment]
Haha, no worry. I was going to fix @jasmainak branch and use this branch as a pull-request.

**Comment by jasmainak** [comment]
@titipata can you also take care of removing the existing notebooks once you have added the content? I will then go ahead and see if I can do continuous integration of the examples with CircleCI. That way examples won't break.

**Comment by jasmainak** [comment]
> Thought plan was to have @titipata submit new PR

some github terminology for titles. WIP: work in progress. MRG: ready to merge. MRG + 1: ready to merge and +1 for merge from one collaborator. MRG + 2: ready to merge and +1 from two collaborators. It means it really is ready to merge :)

the title is edited during the the course of a PR

**Comment by titipata** [comment]
For sure, I can take care of notebooks and content @jasmainak.

**Comment by pavanramkumar** [comment]
@jasmainak awesome! you're ready to write a how-to book on github project management :))

**Pull request merged**
