### PR TITLE
Refactored variable names (issue #92)

### PR DESCRIPTION
**Pull request by tallesventura**
I refactored some variable names on the example and test files so that same objects have same variable names. (issue #92).

### CODE REVIEW

**Comment by titipata** [comment]
Thanks @tallesventura this looks good to me :) cc. @pavanramkumar @jasmainak

**Comment by jasmainak** [comment]
LGTM ! should we merge #91 first @titipata ?

**Comment by pavanramkumar** [comment]
Thanks @tallesventura ! Nice way to warm up!

**Comment by titipata** [comment]
@jasmainak, yeah, I think we can merge https://github.com/pavanramkumar/pyglmnet/pull/91 and follow by this PR.

**Comment by jasmainak** [comment]
okay time to rebase now :)

```sh
$ git fetch master:master_for_rebase
$ git rebase master_for_rebase
```

**Comment by pavanramkumar** [comment]
thanks @tallesventura 
closes #92

**Pull request merged**
