### PR TITLE
add travis build info to readme

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by jasmainak** [comment]
I added build info to README so that we are sure tests pass even when we do a direct commit to master ...

**Comment by pavanramkumar** [comment]
@jasmainak when I ran nosetests before committing it passed all the tests. Is the failure due to flake8?

**Comment by jasmainak** [comment]
yep, the failure is due to `flake8`. What editor are you using? If you are using `sublime` you can install `python flake8 lint` using the sublime package manager. If you are using spyder, there is an option in preferences to enable flake8 checking. You can also run it directly from the command line. `$ flake8 files.py`

**Comment by pavanramkumar** [comment]
Thanks! I'm using atom but I believe pylint can be installed. Will do this afternoon

**Pull request merged**
